# Execute the grasping of a Franka gripper

# Requests
# close_width_percentage: Should be within the range [0, 1]. 0 for fully open, 1 for fully close.
#                         For the real gripper, fully open width is 0.08 m.
# speed_percentage: Moving speed percentage of the finger regarding the maximum speed in range [0, 0.5] m/s
# force_percentage: Grasping force percentage regarding the maximum force in range [0, 70] N.

float64 close_width_percentage
float64 speed_percentage
float64 force_percentage
---
uint8 SUCCEEDED=0
uint8 FAILED=1
uint8 result_status